KBC-1644 teradata interfaces
keboola/php-table-backend-utils pull request #28
Opened 2021-07-13 07:46 UTC by jirkasemmler

2021-07-14 11:55 UTC, jirkasemmler commented on composer.json
> +        "keboola/php-datatypes": "dev-jirka-kbc-1644-teradata-support as 4.x.x-dev",
odstranim s dotahnutyma datatypes . Takhle to aspon prochazi na buildu

2021-07-15 07:11 UTC, zajca requested changes
Vypadá to dost dobře, nahodil sem pár připomínek ještě si stím zkusím pohrát.

2021-07-15 07:11 UTC, zajca commented on tests/Functional/Table/Teradata/TeradataTableQueryBuilderTest.php
> +        array $PKs,
kurník na to není CS? nějaké nor uppercase var names.

2021-07-15 07:11 UTC, zajca commented on tests/Unit/Table/Teradata/TeradataTableQueryBuilderTest.php
> + * @covers SynapseTableReflection
```suggestion
 * @covers TeradataTableQueryBuilder
```

2021-07-15 07:11 UTC, zajca commented on tests/Functional/Table/Teradata/TeradataTableReflectionTest.php
> + * @covers SynapseTableReflection
```suggestion
 * @covers TeradataTableReflection
```

2021-07-15 07:11 UTC, zajca commented on tests/Functional/Table/Teradata/TeradataTableQueryBuilderTest.php
> + * @covers SynapseTableReflection
```suggestion
 * @covers TeradataTableQueryBuilder
```

2021-07-15 07:27 UTC, jirkasemmler commented on src/Table/TableQueryBuilderInterface.php
> +    public function getRenameTableCommand(string $dbName, string $sourceTableName, string $newTableName): string;
jaj, to bude nejakej phpstorm magic... sry, fixnu

2021-07-15 07:42 UTC, jirkasemmler commented on src/Collection.php
> +    public static function extractByKey(array $data, string $key): array
puvodne jsem ho pouzil vicekrat, pak to prepsal a helper zbyl. Ted na to mam asi 2 nebo 3 pouziti, tak mi to dava smysl. Chces to nekam presunout?

2021-07-15 07:48 UTC, jirkasemmler commented on src/Column/Teradata/TeradataColumn.php
> +                'length' => '4000', // max value is 32000
dal jsem tam 32k, ale jeste se musime o tom pobavit, protoze odlisne charsety maji odlisne limity. Nejen tady

2021-07-15 11:10 UTC, jirkasemmler commented on src/Collection.php
> +    public static function extractByKey(array $data, string $key): array
presunuto do DataHelperu

2021-07-15 11:10 UTC, jirkasemmler commented on src/Column/Teradata/TeradataColumn.php
> +                'length' => '4000', // max value is 32000
davam 32k, budeme muset pak resit podle charsetu

2021-07-15 13:10 UTC, zajca requested changes
Ještě by si ten DataHelper zaslůžil unit test a bude to asi cajk, zkusil sem do toho ťukat, ale nic moc nem nenašel ověříme to až v boji :)

2021-07-16 11:23 UTC, zajca commented
Je to cajk, jen ti spadl test :) Předpokládám, že změna v datatypes, dobrý důvod proč to nemerdžovat s tů dev branchí.

2021-07-19 16:44 UTC, jirkasemmler commented
doplnim vecer jeste nejake testy ale takto bych to mergnul (teda az mergneme ten dataypes at je tam master)

2021-07-20 13:43 UTC, zajca reviewed
Je to podle mě v pohodě merdž bych udělal až releasnem datatypes. Jinak máš :+1:

2021-07-20 14:05 UTC, zajca approved these changes

2021-07-22 08:37 UTC, merged