KBC-2902 Synapse uppercase
keboola/php-table-backend-utils pull request #78
Opened 2022-08-31 13:22 UTC by zajca

2022-09-01 13:10 UTC, jirkasemmler requested changes
napadlo me jeste ejstli bychom to nechteli rovnou narvat do QuoteIdentifier? trochu masivni reseni, ale zase by to pokrylo dost usecasu

2022-09-01 13:10 UTC, jirkasemmler commented on src/Table/SynapseTableQueryBuilder.php
>              if ($column->getColumnName() === ColumnInterface::TIMESTAMP_COLUMN_NAME) {
nechceme porovnavat oboji UPPER?

2022-09-01 13:17 UTC, zajca commented on src/Table/SynapseTableQueryBuilder.php
> +        $tableName = CaseConverter::stringToUpper($tableName);
Ne tam sa používá SynapseColumn ten už dělá upper v constructoru

2022-09-01 13:24 UTC, zajca commented on src/Table/SynapseTableQueryBuilder.php
>              if ($column->getColumnName() === ColumnInterface::TIMESTAMP_COLUMN_NAME) {
https://github.com/keboola/php-table-backend-utils/pull/78/commits/292bebc9a3fe1490b576b46480b232ee7992fde5

2022-09-01 13:25 UTC, zajca commented
> napadlo me jeste ejstli bychom to nechteli rovnou narvat do QuoteIdentifier? trochu masivni reseni, ale zase by to pokrylo dost usecasu

Tomu sem sa radši vyhnul, nevím jak sa to bude chovat v master databázi a nevím jestli tam není nějaký edge case takže to dělám takto explicitně.

2022-09-01 13:27 UTC, jirkasemmler approved these changes
🤞

2022-09-08 10:57 UTC, zajca commented
Zavírám to, je to hrozně moc práce na connection, přínos je minimální a stejně je potřeba řešit case sensitive vs insensitive porovnání všude možně, které to vyřeší taky.

2022-09-08 10:57 UTC, closed without merging