TER-18 Table preview filters
keboola/php-table-backend-utils pull request #86
Opened 2022-11-24 17:34 UTC by martinjunger

Jira: TER-18
driver-common: https://github.com/keboola/php-storage-driver-common/pull/16
driver-teradata:

2022-11-29 09:14 UTC, jirkasemmler requested changes
malickosti

2022-11-29 09:14 UTC, jirkasemmler commented on src/Connection/Teradata/TeradataPlatform.php
> +                '/^(SELECT\b)/im',
nebylo by moudre tam pridat jeste `\s*` aby pred tim selectem mohl byt nejakej bilej znak? jen z defensivnich duvodu, kdyby se nekdo pri nejake query seknul s odradkovanim nebo tak neco

2022-11-29 09:14 UTC, jirkasemmler commented on src/Connection/Teradata/TeradataPlatform.php
> +        // TODO offset
asi bych zrusil todo, na to prdime

2022-11-30 15:55 UTC, martinjunger commented on src/Connection/Teradata/TeradataPlatform.php
> +                '/^(SELECT\b)/im',
ale jo, muze byt - pridano

2022-11-30 15:55 UTC, martinjunger commented on src/Connection/Teradata/TeradataPlatform.php
> +        // TODO offset
odebrano

2022-12-01 11:32 UTC, jirkasemmler approved these changes
lgtm

2022-12-02 09:59 UTC, merged